Added possibility of uploading user picture from image intent
wsv-accidis/tmeit-android pull request #30
Opened 2017-02-16 14:49 UTC by RickardZwahlen

2017-02-16 15:10 UTC, loffa requested changes
Make code more unmutable

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		}
Function could take the intent as an argument instead.

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		Bundle extras = intent.getExtras();
Doing as above would remove this duplicated code

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		Intent intent = getIntent();
Intent can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		Bundle extras = intent.getExtras();
bundle can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		ClipData data = intent.getClipData();
data can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +			Uri sourceURI =data.getItemAt(0).getUri();
sourceUri can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		UploadPhotoFragment uploadPhotoFragment = new UploadPhotoFragment();
uploadPhotoFragment can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/FinishUploadPhotoFragment.java
> +				Bundle bundle = getArguments();
bundle can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/FinishUploadPhotoFragment.java
> +				Fragment membersListFragment = new MembersListFragment();
mainActivity and membersListFragment can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/UploadPhotoFragment.java
> +		Bundle bundle = getArguments();
bundle can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/UploadPhotoFragment.java
> +			String uri = getArguments().getString(PHOTO);
uri can be declared as final

2017-02-16 15:10 UTC, loffa commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/UploadPhotoFragment.java
> +				Intent intent = new Intent();
intent can be declared as final

2017-02-17 16:03 UTC, RickardZwahlen commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		Intent intent = getIntent();
It is a method local variable, and can therefore not be declared final.

2017-02-25 10:46 UTC, wsv-accidis requested changes

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +import android.content.*;
Gör helst inte så här, är det Android Studio som gör så automatiskt? Har inte sett det förut.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		{
Formatering, { tillhör raden ovanför. Använd auto-format i Android Studio så fixar den det åt dig. :)

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		final Intent intent = getIntent();
Lägg en blankrad före så det blir lite space mellan sektionerna.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +	private void setupFromIntent() {
Skicka med `intent` som en parameter istället, du anropade ju redan `getIntent` en gång. Och lägg hela den här metoden i bokstavsordning i klassen med de andra `private`-metoderna.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		intent.getData();
Varför? Du gör inget med resultatet.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		{
Formatering igen.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +			final Uri sourceURI =data.getItemAt(0).getUri();
Formatering, saknar space efter =. Autoformat fixar.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +
Överflödig blankrad före }.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/cropPhoto/CropImageActivity.java
> +}
Formatering.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/UploadPhotoFragment.java
>  /**
Överflödiga blankrader.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/UploadPhotoFragment.java
> +	public static final String PHOTO = "photo";
Av konvention brukar jag prefixa nycklar som används i extras med `EXTRA_`, byt namn till `EXTRA_PHOTO`?

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/UploadPhotoFragment.java
> +			final String uri = getArguments().getString(PHOTO);
Här måste något ha gått fel. Du hämtar `bundle = getArguments()`, sen gör du `getArguments()` igen i onödan, sen kollar du `bundle != null` vilket du redan gjort en gång. Förenkla.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/UploadPhotoFragment.java
> +			if(bundle != null && uri!= null){
Formatering, saknar mellanslag före !=.

2017-02-25 10:46 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/uploadPhoto/UploadPhotoFragment.java
> +		if(bundle != null)
Formatering, { ska vara på denna rad. Autoformat...

2017-02-27 09:47 UTC, RickardZwahlen commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +import android.content.*;
Ja, det måste varit AS som gjorde det, för jag har inte gjort det.

2017-02-27 09:48 UTC, RickardZwahlen commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		{
Jag var orolig för att auto-format skulle förstöra allt, eftersom min lokala style är annorlunda. Men AS kanske använder style-filen i repon? Jag skulle testat i alla fall, men glömde bort det :)

2017-02-27 17:16 UTC, wsv-accidis commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +		{
Det finns ingen style-fil för sånt här, det är formaterat enligt Android Studios standard, som i sin tur bygger (tror jag) på kodstilen från AOSP :)

2017-02-27 23:29 UTC, RickardZwahlen commented on app/src/main/java/se/tmeit/app/ui/MainActivity.java
> +import android.content.*;
Verkar som att AS inkluderar allt om man har >=5 specifika imports. Om man lägger till en till ovan alltså.

2017-02-28 09:25 UTC, wsv-accidis approved these changes

2017-02-28 09:26 UTC, merged